$(document).ready(function(){
    $("designIcon").click(function(){
        $("imgDesign").toggle();
        $("paragraphDesign").toggle();
    })
});
$(document).ready(function(){
    $("devIcon").click(function(){
        $("imgDev").toggle();
        $("paragraphDev").toggle();
    })
});
$(document).ready(function(){
    $("productIcon").click(function(){
        $("imgProduct").toggle();
        $("paragraphProduct").toggle();
    })
});