$(document).ready(function(){
    $("#designIcon").click(function(){
        $("#imgDesign").toggle();
        $("#paragraphDesign").toggle();
    })
    $("#devIcon").click(function(){
        $("#imgDev").toggle();
        $("#paragraphDev").toggle();
    });
    $("#productIcon").click(function(){
        $("#imgProduct").toggle();
        $("#paragraphProduct").toggle();
    });
});